spring.application.name=OdysseyTravelPlanningWebsiteBackendApplication
spring.data.mongodb.uri=mongodb+srv://root:Hasindu1234H@odyssey.lr8xr.mongodb.net/odyssey?retryWrites=true&w=majority&ssl=true
server.port=9090
stripe.secret.key=sk_test_51Oh8UwKePWxvmPbIqxsBPY87uQbT2aVX87BFIPecwpLSAK88T4HtIacjVnt1yZ0AD9VVBUBgKcUwRohkbc5BHXu900ShlCCvYJ